language: php

php:
  - 7.0

branches:
  only:
    - master
    - development
    - /^feature\/.+$/

before_script:
 - git checkout $TRAVIS_BRANCH
 - composer self-update
 - mkdir -p vendor/bin
 - composer install -o --prefer-dist --no-interaction
 - mkdir build/logs

script:
 - php vendor/bin/phpunit -c build/

after_success:
 - travis_retry php vendor/bin/coveralls -v --exclude-no-stmt

notifications:
  slack: fortunesolutions:PoLjMJuARdFicBIEPzdNrZ96
